services:
  - type: web
    name: pls-crm
    runtime: node
    buildCommand: npm run build
    startCommand: npx serve -s dist -l $PORT
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
